// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Journal struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	EntryDate    pgtype.Date
	DidToday     pgtype.Text
	LearnedToday pgtype.Text
	FilePath     pgtype.Text
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type User struct {
	ID           pgtype.UUID
	Name         string
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamp
}
