// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJournal = `-- name: CreateJournal :one
INSERT INTO journals (user_id, entry_date, did_today, learned_today)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, entry_date, did_today, learned_today, created_at, updated_at
`

type CreateJournalParams struct {
	UserID       pgtype.UUID
	EntryDate    pgtype.Date
	DidToday     pgtype.Text
	LearnedToday pgtype.Text
}

func (q *Queries) CreateJournal(ctx context.Context, arg CreateJournalParams) (Journal, error) {
	row := q.db.QueryRow(ctx, createJournal,
		arg.UserID,
		arg.EntryDate,
		arg.DidToday,
		arg.LearnedToday,
	)
	var i Journal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EntryDate,
		&i.DidToday,
		&i.LearnedToday,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, password_hash)
VALUES ($1, $2, $3)
RETURNING id, name, email, password_hash, created_at
`

type CreateUserParams struct {
	Name         string
	Email        string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const deleteJournal = `-- name: DeleteJournal :exec
DELETE FROM journals
WHERE id = $1 AND user_id = $2
`

type DeleteJournalParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteJournal(ctx context.Context, arg DeleteJournalParams) error {
	_, err := q.db.Exec(ctx, deleteJournal, arg.ID, arg.UserID)
	return err
}

const getJournalsByUser = `-- name: GetJournalsByUser :many
SELECT id, user_id, entry_date, did_today, learned_today, created_at, updated_at FROM journals
WHERE user_id = $1
ORDER BY entry_date DESC
`

func (q *Queries) GetJournalsByUser(ctx context.Context, userID pgtype.UUID) ([]Journal, error) {
	rows, err := q.db.Query(ctx, getJournalsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Journal
	for rows.Next() {
		var i Journal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EntryDate,
			&i.DidToday,
			&i.LearnedToday,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password_hash, created_at FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}
