// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTagToJournal = `-- name: AddTagToJournal :exec

INSERT INTO journal_tags (journal_id, tag_id)
VALUES ($1, $2)
ON CONFLICT (journal_id, tag_id) DO NOTHING
`

type AddTagToJournalParams struct {
	JournalID int32 `json:"journal_id"`
	TagID     int32 `json:"tag_id"`
}

// ========================
// JOURNAL TAGS
// ========================
func (q *Queries) AddTagToJournal(ctx context.Context, arg AddTagToJournalParams) error {
	_, err := q.db.Exec(ctx, addTagToJournal, arg.JournalID, arg.TagID)
	return err
}

const countJournalsByUser = `-- name: CountJournalsByUser :one
SELECT COUNT(*) FROM journals
WHERE user_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) CountJournalsByUser(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countJournalsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAchievement = `-- name: CreateAchievement :one

INSERT INTO achievements (journal_id, user_id, title, description, impact, importance, achieved_date)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, journal_id, user_id, title, description, impact, importance, achieved_date, created_at, updated_at
`

type CreateAchievementParams struct {
	JournalID    int32               `json:"journal_id"`
	UserID       int32               `json:"user_id"`
	Title        string              `json:"title"`
	Description  pgtype.Text         `json:"description"`
	Impact       pgtype.Text         `json:"impact"`
	Importance   NullImportanceLevel `json:"importance"`
	AchievedDate pgtype.Date         `json:"achieved_date"`
}

// ========================
// ACHIEVEMENTS
// ========================
func (q *Queries) CreateAchievement(ctx context.Context, arg CreateAchievementParams) (Achievement, error) {
	row := q.db.QueryRow(ctx, createAchievement,
		arg.JournalID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Impact,
		arg.Importance,
		arg.AchievedDate,
	)
	var i Achievement
	err := row.Scan(
		&i.ID,
		&i.JournalID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Impact,
		&i.Importance,
		&i.AchievedDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAttachment = `-- name: CreateAttachment :one

INSERT INTO journal_attachments (
  journal_id, file_path, file_name, file_type, file_size, 
  storage_key, thumbnail_path, checksum, uploaded_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, journal_id, file_path, file_name, file_type, file_size, storage_key, thumbnail_path, checksum, uploaded_by, created_at
`

type CreateAttachmentParams struct {
	JournalID     int32       `json:"journal_id"`
	FilePath      string      `json:"file_path"`
	FileName      pgtype.Text `json:"file_name"`
	FileType      pgtype.Text `json:"file_type"`
	FileSize      pgtype.Int4 `json:"file_size"`
	StorageKey    pgtype.Text `json:"storage_key"`
	ThumbnailPath pgtype.Text `json:"thumbnail_path"`
	Checksum      pgtype.Text `json:"checksum"`
	UploadedBy    pgtype.Int4 `json:"uploaded_by"`
}

// ========================
// JOURNAL ATTACHMENTS
// ========================
func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (JournalAttachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.JournalID,
		arg.FilePath,
		arg.FileName,
		arg.FileType,
		arg.FileSize,
		arg.StorageKey,
		arg.ThumbnailPath,
		arg.Checksum,
		arg.UploadedBy,
	)
	var i JournalAttachment
	err := row.Scan(
		&i.ID,
		&i.JournalID,
		&i.FilePath,
		&i.FileName,
		&i.FileType,
		&i.FileSize,
		&i.StorageKey,
		&i.ThumbnailPath,
		&i.Checksum,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createJournal = `-- name: CreateJournal :one

INSERT INTO journals (
    user_id, entry_date, title, did_today, learned_today,
    category, blockers, next_plan,
    visibility, kpi_period_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, entry_date, title, did_today, learned_today, category, blockers, next_plan, visibility, kpi_period_id, created_at, updated_at, deleted_at
`

type CreateJournalParams struct {
	UserID       int32                 `json:"user_id"`
	EntryDate    pgtype.Date           `json:"entry_date"`
	Title        pgtype.Text           `json:"title"`
	DidToday     pgtype.Text           `json:"did_today"`
	LearnedToday pgtype.Text           `json:"learned_today"`
	Category     NullJournalCategory   `json:"category"`
	Blockers     pgtype.Text           `json:"blockers"`
	NextPlan     pgtype.Text           `json:"next_plan"`
	Visibility   NullJournalVisibility `json:"visibility"`
	KpiPeriodID  pgtype.Int4           `json:"kpi_period_id"`
}

// ========================
// JOURNALS
// ========================
func (q *Queries) CreateJournal(ctx context.Context, arg CreateJournalParams) (Journal, error) {
	row := q.db.QueryRow(ctx, createJournal,
		arg.UserID,
		arg.EntryDate,
		arg.Title,
		arg.DidToday,
		arg.LearnedToday,
		arg.Category,
		arg.Blockers,
		arg.NextPlan,
		arg.Visibility,
		arg.KpiPeriodID,
	)
	var i Journal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EntryDate,
		&i.Title,
		&i.DidToday,
		&i.LearnedToday,
		&i.Category,
		&i.Blockers,
		&i.NextPlan,
		&i.Visibility,
		&i.KpiPeriodID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createKPI = `-- name: CreateKPI :one

INSERT INTO kpi_periods (name, start_date, end_date, team_id)
VALUES ($1, $2, $3, $4)
RETURNING id, name, start_date, end_date, team_id, created_at
`

type CreateKPIParams struct {
	Name      string      `json:"name"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
	TeamID    pgtype.Int4 `json:"team_id"`
}

// ========================
// KPI / DASHBOARD
// ========================
func (q *Queries) CreateKPI(ctx context.Context, arg CreateKPIParams) (KpiPeriod, error) {
	row := q.db.QueryRow(ctx, createKPI,
		arg.Name,
		arg.StartDate,
		arg.EndDate,
		arg.TeamID,
	)
	var i KpiPeriod
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.TeamID,
		&i.CreatedAt,
	)
	return i, err
}

const createTag = `-- name: CreateTag :one

INSERT INTO tags (name) VALUES ($1)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name, created_at
`

// ========================
// TAGS
// ========================
func (q *Queries) CreateTag(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const createTeam = `-- name: CreateTeam :one

INSERT INTO teams (name)
VALUES ($1)
RETURNING id, name, created_at, manager_id
`

// ========================
// TEAMS
// ========================
func (q *Queries) CreateTeam(ctx context.Context, name string) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, name)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.ManagerID,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (name, email, password_hash, team_id)
VALUES ($1, $2, $3, $4)
RETURNING id, name, email, password_hash, role, team_id, is_active, created_at
`

type CreateUserParams struct {
	Name         string      `json:"name"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	TeamID       pgtype.Int4 `json:"team_id"`
}

// ========================
// USERS
// ========================
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.TeamID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.TeamID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAchievement = `-- name: DeleteAchievement :exec
DELETE FROM achievements
WHERE id = $1 AND user_id = $2
`

type DeleteAchievementParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteAchievement(ctx context.Context, arg DeleteAchievementParams) error {
	_, err := q.db.Exec(ctx, deleteAchievement, arg.ID, arg.UserID)
	return err
}

const deleteAllAttachmentsByJournal = `-- name: DeleteAllAttachmentsByJournal :exec
DELETE FROM journal_attachments
WHERE journal_id = $1
`

func (q *Queries) DeleteAllAttachmentsByJournal(ctx context.Context, journalID int32) error {
	_, err := q.db.Exec(ctx, deleteAllAttachmentsByJournal, journalID)
	return err
}

const deleteAttachment = `-- name: DeleteAttachment :exec
DELETE FROM journal_attachments
WHERE id = $1
  AND journal_id = $2
`

type DeleteAttachmentParams struct {
	ID        int32 `json:"id"`
	JournalID int32 `json:"journal_id"`
}

func (q *Queries) DeleteAttachment(ctx context.Context, arg DeleteAttachmentParams) error {
	_, err := q.db.Exec(ctx, deleteAttachment, arg.ID, arg.JournalID)
	return err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = $1
`

func (q *Queries) DeleteTag(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteTag, id)
	return err
}

const getAchievementByID = `-- name: GetAchievementByID :one
SELECT id, journal_id, user_id, title, description, impact, importance, achieved_date, created_at, updated_at FROM achievements
WHERE id = $1 AND user_id = $2
`

type GetAchievementByIDParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) GetAchievementByID(ctx context.Context, arg GetAchievementByIDParams) (Achievement, error) {
	row := q.db.QueryRow(ctx, getAchievementByID, arg.ID, arg.UserID)
	var i Achievement
	err := row.Scan(
		&i.ID,
		&i.JournalID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Impact,
		&i.Importance,
		&i.AchievedDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAchievementsByDateRange = `-- name: GetAchievementsByDateRange :many
SELECT id, journal_id, user_id, title, description, impact, importance, achieved_date, created_at, updated_at FROM achievements
WHERE user_id = $1
  AND achieved_date BETWEEN $2 AND $3
ORDER BY achieved_date DESC
`

type GetAchievementsByDateRangeParams struct {
	UserID         int32       `json:"user_id"`
	AchievedDate   pgtype.Date `json:"achieved_date"`
	AchievedDate_2 pgtype.Date `json:"achieved_date_2"`
}

func (q *Queries) GetAchievementsByDateRange(ctx context.Context, arg GetAchievementsByDateRangeParams) ([]Achievement, error) {
	rows, err := q.db.Query(ctx, getAchievementsByDateRange, arg.UserID, arg.AchievedDate, arg.AchievedDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Achievement
	for rows.Next() {
		var i Achievement
		if err := rows.Scan(
			&i.ID,
			&i.JournalID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Impact,
			&i.Importance,
			&i.AchievedDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAchievementsByImportance = `-- name: GetAchievementsByImportance :many
SELECT id, journal_id, user_id, title, description, impact, importance, achieved_date, created_at, updated_at FROM achievements
WHERE user_id = $1
  AND importance = $2
ORDER BY achieved_date DESC NULLS LAST
`

type GetAchievementsByImportanceParams struct {
	UserID     int32               `json:"user_id"`
	Importance NullImportanceLevel `json:"importance"`
}

func (q *Queries) GetAchievementsByImportance(ctx context.Context, arg GetAchievementsByImportanceParams) ([]Achievement, error) {
	rows, err := q.db.Query(ctx, getAchievementsByImportance, arg.UserID, arg.Importance)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Achievement
	for rows.Next() {
		var i Achievement
		if err := rows.Scan(
			&i.ID,
			&i.JournalID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Impact,
			&i.Importance,
			&i.AchievedDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAchievementsByJournal = `-- name: GetAchievementsByJournal :many
SELECT id, journal_id, user_id, title, description, impact, importance, achieved_date, created_at, updated_at FROM achievements
WHERE journal_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetAchievementsByJournal(ctx context.Context, journalID int32) ([]Achievement, error) {
	rows, err := q.db.Query(ctx, getAchievementsByJournal, journalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Achievement
	for rows.Next() {
		var i Achievement
		if err := rows.Scan(
			&i.ID,
			&i.JournalID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Impact,
			&i.Importance,
			&i.AchievedDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAchievementsByUser = `-- name: GetAchievementsByUser :many
SELECT id, journal_id, user_id, title, description, impact, importance, achieved_date, created_at, updated_at FROM achievements
WHERE user_id = $1
ORDER BY achieved_date DESC NULLS LAST, created_at DESC
`

func (q *Queries) GetAchievementsByUser(ctx context.Context, userID int32) ([]Achievement, error) {
	rows, err := q.db.Query(ctx, getAchievementsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Achievement
	for rows.Next() {
		var i Achievement
		if err := rows.Scan(
			&i.ID,
			&i.JournalID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Impact,
			&i.Importance,
			&i.AchievedDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAchievementsByUserPaginated = `-- name: GetAchievementsByUserPaginated :many
SELECT id, journal_id, user_id, title, description, impact, importance, achieved_date, created_at, updated_at FROM achievements
WHERE user_id = $1
ORDER BY achieved_date DESC NULLS LAST, created_at DESC
LIMIT $2 OFFSET $3
`

type GetAchievementsByUserPaginatedParams struct {
	UserID int32 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAchievementsByUserPaginated(ctx context.Context, arg GetAchievementsByUserPaginatedParams) ([]Achievement, error) {
	rows, err := q.db.Query(ctx, getAchievementsByUserPaginated, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Achievement
	for rows.Next() {
		var i Achievement
		if err := rows.Scan(
			&i.ID,
			&i.JournalID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Impact,
			&i.Importance,
			&i.AchievedDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveKPIByTeam = `-- name: GetActiveKPIByTeam :one
SELECT id, name, start_date, end_date, team_id, created_at FROM kpi_periods
WHERE team_id = $1
  AND start_date <= NOW()
  AND end_date >= NOW()
ORDER BY start_date DESC
LIMIT 1
`

func (q *Queries) GetActiveKPIByTeam(ctx context.Context, teamID pgtype.Int4) (KpiPeriod, error) {
	row := q.db.QueryRow(ctx, getActiveKPIByTeam, teamID)
	var i KpiPeriod
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.TeamID,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveKPIByUser = `-- name: GetActiveKPIByUser :one
SELECT kp.id, kp.name, kp.start_date, kp.end_date, kp.team_id, kp.created_at FROM kpi_periods kp
JOIN users u ON u.team_id = kp.team_id
WHERE u.id = $1
  AND kp.start_date <= NOW()
  AND kp.end_date >= NOW()
ORDER BY kp.start_date DESC
LIMIT 1
`

func (q *Queries) GetActiveKPIByUser(ctx context.Context, id int32) (KpiPeriod, error) {
	row := q.db.QueryRow(ctx, getActiveKPIByUser, id)
	var i KpiPeriod
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.TeamID,
		&i.CreatedAt,
	)
	return i, err
}

const getAttachmentByID = `-- name: GetAttachmentByID :one
SELECT id, journal_id, file_path, file_name, file_type, file_size, storage_key, thumbnail_path, checksum, uploaded_by, created_at FROM journal_attachments
WHERE id = $1
`

func (q *Queries) GetAttachmentByID(ctx context.Context, id int32) (JournalAttachment, error) {
	row := q.db.QueryRow(ctx, getAttachmentByID, id)
	var i JournalAttachment
	err := row.Scan(
		&i.ID,
		&i.JournalID,
		&i.FilePath,
		&i.FileName,
		&i.FileType,
		&i.FileSize,
		&i.StorageKey,
		&i.ThumbnailPath,
		&i.Checksum,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getAttachmentsByJournal = `-- name: GetAttachmentsByJournal :many
SELECT id, journal_id, file_path, file_name, file_type, file_size, storage_key, thumbnail_path, checksum, uploaded_by, created_at FROM journal_attachments
WHERE journal_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetAttachmentsByJournal(ctx context.Context, journalID int32) ([]JournalAttachment, error) {
	rows, err := q.db.Query(ctx, getAttachmentsByJournal, journalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JournalAttachment
	for rows.Next() {
		var i JournalAttachment
		if err := rows.Scan(
			&i.ID,
			&i.JournalID,
			&i.FilePath,
			&i.FileName,
			&i.FileType,
			&i.FileSize,
			&i.StorageKey,
			&i.ThumbnailPath,
			&i.Checksum,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJournalByID = `-- name: GetJournalByID :one
SELECT id, user_id, entry_date, title, did_today, learned_today, category, blockers, next_plan, visibility, kpi_period_id, created_at, updated_at, deleted_at FROM journals
WHERE id = $1
  AND user_id = $2
  AND deleted_at IS NULL
`

type GetJournalByIDParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) GetJournalByID(ctx context.Context, arg GetJournalByIDParams) (Journal, error) {
	row := q.db.QueryRow(ctx, getJournalByID, arg.ID, arg.UserID)
	var i Journal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EntryDate,
		&i.Title,
		&i.DidToday,
		&i.LearnedToday,
		&i.Category,
		&i.Blockers,
		&i.NextPlan,
		&i.Visibility,
		&i.KpiPeriodID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getJournalsByCategory = `-- name: GetJournalsByCategory :many
SELECT id, user_id, entry_date, title, did_today, learned_today, category, blockers, next_plan, visibility, kpi_period_id, created_at, updated_at, deleted_at FROM journals
WHERE user_id = $1
  AND category = $2
  AND deleted_at IS NULL
ORDER BY entry_date DESC
`

type GetJournalsByCategoryParams struct {
	UserID   int32               `json:"user_id"`
	Category NullJournalCategory `json:"category"`
}

func (q *Queries) GetJournalsByCategory(ctx context.Context, arg GetJournalsByCategoryParams) ([]Journal, error) {
	rows, err := q.db.Query(ctx, getJournalsByCategory, arg.UserID, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Journal
	for rows.Next() {
		var i Journal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EntryDate,
			&i.Title,
			&i.DidToday,
			&i.LearnedToday,
			&i.Category,
			&i.Blockers,
			&i.NextPlan,
			&i.Visibility,
			&i.KpiPeriodID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJournalsByDate = `-- name: GetJournalsByDate :many
SELECT id, user_id, entry_date, title, did_today, learned_today, category, blockers, next_plan, visibility, kpi_period_id, created_at, updated_at, deleted_at FROM journals
WHERE user_id = $1
  AND entry_date = $2
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

type GetJournalsByDateParams struct {
	UserID    int32       `json:"user_id"`
	EntryDate pgtype.Date `json:"entry_date"`
}

func (q *Queries) GetJournalsByDate(ctx context.Context, arg GetJournalsByDateParams) ([]Journal, error) {
	rows, err := q.db.Query(ctx, getJournalsByDate, arg.UserID, arg.EntryDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Journal
	for rows.Next() {
		var i Journal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EntryDate,
			&i.Title,
			&i.DidToday,
			&i.LearnedToday,
			&i.Category,
			&i.Blockers,
			&i.NextPlan,
			&i.Visibility,
			&i.KpiPeriodID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJournalsByDateRange = `-- name: GetJournalsByDateRange :many
SELECT id, user_id, entry_date, title, did_today, learned_today, category, blockers, next_plan, visibility, kpi_period_id, created_at, updated_at, deleted_at FROM journals
WHERE user_id = $1
  AND entry_date BETWEEN $2 AND $3
  AND deleted_at IS NULL
ORDER BY entry_date DESC
`

type GetJournalsByDateRangeParams struct {
	UserID      int32       `json:"user_id"`
	EntryDate   pgtype.Date `json:"entry_date"`
	EntryDate_2 pgtype.Date `json:"entry_date_2"`
}

func (q *Queries) GetJournalsByDateRange(ctx context.Context, arg GetJournalsByDateRangeParams) ([]Journal, error) {
	rows, err := q.db.Query(ctx, getJournalsByDateRange, arg.UserID, arg.EntryDate, arg.EntryDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Journal
	for rows.Next() {
		var i Journal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EntryDate,
			&i.Title,
			&i.DidToday,
			&i.LearnedToday,
			&i.Category,
			&i.Blockers,
			&i.NextPlan,
			&i.Visibility,
			&i.KpiPeriodID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJournalsByTag = `-- name: GetJournalsByTag :many
SELECT j.id, j.user_id, j.entry_date, j.title, j.did_today, j.learned_today,
       j.category, j.blockers, j.next_plan,
       j.visibility, j.kpi_period_id, j.created_at, j.updated_at, j.deleted_at
FROM journals j
JOIN journal_tags jt ON jt.journal_id = j.id
WHERE jt.tag_id = $1
  AND j.user_id = $2
  AND j.deleted_at IS NULL
ORDER BY j.entry_date DESC
`

type GetJournalsByTagParams struct {
	TagID  int32 `json:"tag_id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) GetJournalsByTag(ctx context.Context, arg GetJournalsByTagParams) ([]Journal, error) {
	rows, err := q.db.Query(ctx, getJournalsByTag, arg.TagID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Journal
	for rows.Next() {
		var i Journal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EntryDate,
			&i.Title,
			&i.DidToday,
			&i.LearnedToday,
			&i.Category,
			&i.Blockers,
			&i.NextPlan,
			&i.Visibility,
			&i.KpiPeriodID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJournalsByTitle = `-- name: GetJournalsByTitle :many
SELECT id, user_id, entry_date, title, did_today, learned_today, category, blockers, next_plan, visibility, kpi_period_id, created_at, updated_at, deleted_at FROM journals
WHERE user_id = $1
  AND title ILIKE '%' || $2 || '%'
  AND deleted_at IS NULL
ORDER BY entry_date DESC
`

type GetJournalsByTitleParams struct {
	UserID  int32       `json:"user_id"`
	Column2 pgtype.Text `json:"column_2"`
}

func (q *Queries) GetJournalsByTitle(ctx context.Context, arg GetJournalsByTitleParams) ([]Journal, error) {
	rows, err := q.db.Query(ctx, getJournalsByTitle, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Journal
	for rows.Next() {
		var i Journal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EntryDate,
			&i.Title,
			&i.DidToday,
			&i.LearnedToday,
			&i.Category,
			&i.Blockers,
			&i.NextPlan,
			&i.Visibility,
			&i.KpiPeriodID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJournalsByUser = `-- name: GetJournalsByUser :many
SELECT id, user_id, entry_date, title, did_today, learned_today, category, blockers, next_plan, visibility, kpi_period_id, created_at, updated_at, deleted_at FROM journals
WHERE user_id = $1
  AND deleted_at IS NULL
ORDER BY entry_date DESC
`

func (q *Queries) GetJournalsByUser(ctx context.Context, userID int32) ([]Journal, error) {
	rows, err := q.db.Query(ctx, getJournalsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Journal
	for rows.Next() {
		var i Journal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EntryDate,
			&i.Title,
			&i.DidToday,
			&i.LearnedToday,
			&i.Category,
			&i.Blockers,
			&i.NextPlan,
			&i.Visibility,
			&i.KpiPeriodID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJournalsByUserPaginated = `-- name: GetJournalsByUserPaginated :many
SELECT id, user_id, entry_date, title, did_today, learned_today, category, blockers, next_plan, visibility, kpi_period_id, created_at, updated_at, deleted_at FROM journals
WHERE user_id = $1
  AND deleted_at IS NULL
ORDER BY entry_date DESC
LIMIT $2 OFFSET $3
`

type GetJournalsByUserPaginatedParams struct {
	UserID int32 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetJournalsByUserPaginated(ctx context.Context, arg GetJournalsByUserPaginatedParams) ([]Journal, error) {
	rows, err := q.db.Query(ctx, getJournalsByUserPaginated, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Journal
	for rows.Next() {
		var i Journal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EntryDate,
			&i.Title,
			&i.DidToday,
			&i.LearnedToday,
			&i.Category,
			&i.Blockers,
			&i.NextPlan,
			&i.Visibility,
			&i.KpiPeriodID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getKPIByID = `-- name: GetKPIByID :one
SELECT id, name, start_date, end_date, team_id, created_at FROM kpi_periods
WHERE id = $1
`

func (q *Queries) GetKPIByID(ctx context.Context, id int32) (KpiPeriod, error) {
	row := q.db.QueryRow(ctx, getKPIByID, id)
	var i KpiPeriod
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.TeamID,
		&i.CreatedAt,
	)
	return i, err
}

const getKPISummaryByMonth = `-- name: GetKPISummaryByMonth :many
SELECT user_id, team_id, kpi_period_id, week, month, total_active_days, total_entries, top_category FROM journal_kpi_summary
WHERE user_id = $1
  AND month = date_trunc('month', $2::timestamp with time zone)
ORDER BY week ASC
`

type GetKPISummaryByMonthParams struct {
	UserID  int32              `json:"user_id"`
	Column2 pgtype.Timestamptz `json:"column_2"`
}

func (q *Queries) GetKPISummaryByMonth(ctx context.Context, arg GetKPISummaryByMonthParams) ([]JournalKpiSummary, error) {
	rows, err := q.db.Query(ctx, getKPISummaryByMonth, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JournalKpiSummary
	for rows.Next() {
		var i JournalKpiSummary
		if err := rows.Scan(
			&i.UserID,
			&i.TeamID,
			&i.KpiPeriodID,
			&i.Week,
			&i.Month,
			&i.TotalActiveDays,
			&i.TotalEntries,
			&i.TopCategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getKPISummaryByUser = `-- name: GetKPISummaryByUser :many
SELECT user_id, team_id, kpi_period_id, week, month, total_active_days, total_entries, top_category FROM journal_kpi_summary
WHERE user_id = $1
ORDER BY month DESC, week DESC
`

func (q *Queries) GetKPISummaryByUser(ctx context.Context, userID int32) ([]JournalKpiSummary, error) {
	rows, err := q.db.Query(ctx, getKPISummaryByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JournalKpiSummary
	for rows.Next() {
		var i JournalKpiSummary
		if err := rows.Scan(
			&i.UserID,
			&i.TeamID,
			&i.KpiPeriodID,
			&i.Week,
			&i.Month,
			&i.TotalActiveDays,
			&i.TotalEntries,
			&i.TopCategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getKPIsByTeam = `-- name: GetKPIsByTeam :many
SELECT id, name, start_date, end_date, team_id, created_at FROM kpi_periods
WHERE team_id = $1
ORDER BY start_date DESC
`

func (q *Queries) GetKPIsByTeam(ctx context.Context, teamID pgtype.Int4) ([]KpiPeriod, error) {
	rows, err := q.db.Query(ctx, getKPIsByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KpiPeriod
	for rows.Next() {
		var i KpiPeriod
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartDate,
			&i.EndDate,
			&i.TeamID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStreakByUser = `-- name: GetStreakByUser :many
SELECT entry_date FROM journals
WHERE user_id = $1
  AND deleted_at IS NULL
ORDER BY entry_date DESC
`

func (q *Queries) GetStreakByUser(ctx context.Context, userID int32) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, getStreakByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Date
	for rows.Next() {
		var entry_date pgtype.Date
		if err := rows.Scan(&entry_date); err != nil {
			return nil, err
		}
		items = append(items, entry_date)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagByID = `-- name: GetTagByID :one
SELECT id, name, created_at FROM tags WHERE id = $1
`

func (q *Queries) GetTagByID(ctx context.Context, id int32) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByID, id)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, name, created_at FROM tags WHERE name = $1
`

func (q *Queries) GetTagByName(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByName, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getTagsByJournal = `-- name: GetTagsByJournal :many
SELECT t.id, t.name, t.created_at FROM tags t
JOIN journal_tags jt ON jt.tag_id = t.id
WHERE jt.journal_id = $1
ORDER BY t.name ASC
`

func (q *Queries) GetTagsByJournal(ctx context.Context, journalID int32) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getTagsByJournal, journalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, name, created_at, manager_id FROM teams
WHERE id = $1
`

func (q *Queries) GetTeamByID(ctx context.Context, id int32) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.ManagerID,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password_hash, role, team_id, is_active, created_at FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.TeamID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, password_hash, role, team_id, is_active, created_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.TeamID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const hardDeleteJournal = `-- name: HardDeleteJournal :exec
DELETE FROM journals
WHERE id = $1
  AND user_id = $2
`

type HardDeleteJournalParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) HardDeleteJournal(ctx context.Context, arg HardDeleteJournalParams) error {
	_, err := q.db.Exec(ctx, hardDeleteJournal, arg.ID, arg.UserID)
	return err
}

const listTags = `-- name: ListTags :many
SELECT id, name, created_at FROM tags ORDER BY name ASC
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTagFromJournal = `-- name: RemoveTagFromJournal :exec
DELETE FROM journal_tags
WHERE journal_id = $1 AND tag_id = $2
`

type RemoveTagFromJournalParams struct {
	JournalID int32 `json:"journal_id"`
	TagID     int32 `json:"tag_id"`
}

func (q *Queries) RemoveTagFromJournal(ctx context.Context, arg RemoveTagFromJournalParams) error {
	_, err := q.db.Exec(ctx, removeTagFromJournal, arg.JournalID, arg.TagID)
	return err
}

const restoreJournal = `-- name: RestoreJournal :exec
UPDATE journals
SET deleted_at = NULL
WHERE id = $1
  AND user_id = $2
  AND deleted_at IS NOT NULL
`

type RestoreJournalParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) RestoreJournal(ctx context.Context, arg RestoreJournalParams) error {
	_, err := q.db.Exec(ctx, restoreJournal, arg.ID, arg.UserID)
	return err
}

const searchJournals = `-- name: SearchJournals :many

SELECT DISTINCT j.id, j.user_id, j.entry_date, j.title, j.did_today, j.learned_today,
       j.category, j.blockers, j.next_plan,
       j.visibility, j.kpi_period_id, j.created_at, j.updated_at, j.deleted_at
FROM journals j
LEFT JOIN journal_tags jt ON jt.journal_id = j.id
LEFT JOIN tags t ON t.id = jt.tag_id
LEFT JOIN achievements a ON a.journal_id = j.id
WHERE j.user_id = $1
  AND j.deleted_at IS NULL
  AND (
    $4::text IS NULL OR $4::text = '' OR (
      j.title ILIKE '%' || $4 || '%'
      OR j.did_today ILIKE '%' || $4 || '%'
      OR j.learned_today ILIKE '%' || $4 || '%'
      OR a.title ILIKE '%' || $4 || '%'
      OR a.impact ILIKE '%' || $4 || '%'
    )
  )
  AND ($5::text IS NULL OR $5::text = '' OR j.category = $5::journal_category)
  AND ($6::text IS NULL OR $6::text = '' OR t.name = $6)
  AND ($7::date IS NULL OR j.entry_date >= $7)
  AND ($8::date IS NULL OR j.entry_date <= $8)
ORDER BY j.entry_date DESC
LIMIT $2 OFFSET $3
`

type SearchJournalsParams struct {
	UserID   int32       `json:"user_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
	Keyword  string      `json:"keyword"`
	Category string      `json:"category"`
	Tag      string      `json:"tag"`
	DateFrom pgtype.Date `json:"date_from"`
	DateTo   pgtype.Date `json:"date_to"`
}

// ========================
// RICH SEARCH
// ========================
func (q *Queries) SearchJournals(ctx context.Context, arg SearchJournalsParams) ([]Journal, error) {
	rows, err := q.db.Query(ctx, searchJournals,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.Keyword,
		arg.Category,
		arg.Tag,
		arg.DateFrom,
		arg.DateTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Journal
	for rows.Next() {
		var i Journal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EntryDate,
			&i.Title,
			&i.DidToday,
			&i.LearnedToday,
			&i.Category,
			&i.Blockers,
			&i.NextPlan,
			&i.Visibility,
			&i.KpiPeriodID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteJournal = `-- name: SoftDeleteJournal :exec
UPDATE journals
SET deleted_at = NOW()
WHERE id = $1
  AND user_id = $2
  AND deleted_at IS NULL
`

type SoftDeleteJournalParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) SoftDeleteJournal(ctx context.Context, arg SoftDeleteJournalParams) error {
	_, err := q.db.Exec(ctx, softDeleteJournal, arg.ID, arg.UserID)
	return err
}

const updateAchievement = `-- name: UpdateAchievement :one
UPDATE achievements
SET
    title         = COALESCE($3, title),
    description   = COALESCE($4, description),
    impact        = COALESCE($5, impact),
    importance    = COALESCE($6, importance),
    achieved_date = COALESCE($7, achieved_date)
WHERE id = $1 AND user_id = $2
RETURNING id, journal_id, user_id, title, description, impact, importance, achieved_date, created_at, updated_at
`

type UpdateAchievementParams struct {
	ID           int32               `json:"id"`
	UserID       int32               `json:"user_id"`
	Title        string              `json:"title"`
	Description  pgtype.Text         `json:"description"`
	Impact       pgtype.Text         `json:"impact"`
	Importance   NullImportanceLevel `json:"importance"`
	AchievedDate pgtype.Date         `json:"achieved_date"`
}

func (q *Queries) UpdateAchievement(ctx context.Context, arg UpdateAchievementParams) (Achievement, error) {
	row := q.db.QueryRow(ctx, updateAchievement,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Impact,
		arg.Importance,
		arg.AchievedDate,
	)
	var i Achievement
	err := row.Scan(
		&i.ID,
		&i.JournalID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Impact,
		&i.Importance,
		&i.AchievedDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateJournal = `-- name: UpdateJournal :one
UPDATE journals
SET
    title           = COALESCE($3, title),
    did_today       = COALESCE($4, did_today),
    learned_today   = COALESCE($5, learned_today),
    category        = COALESCE($6, category),
    blockers        = COALESCE($7, blockers),
    next_plan       = COALESCE($8, next_plan),
    visibility      = COALESCE($9, visibility),
    kpi_period_id   = COALESCE($10, kpi_period_id)
WHERE id = $1
  AND user_id = $2
  AND deleted_at IS NULL
RETURNING id, user_id, entry_date, title, did_today, learned_today, category, blockers, next_plan, visibility, kpi_period_id, created_at, updated_at, deleted_at
`

type UpdateJournalParams struct {
	ID           int32                 `json:"id"`
	UserID       int32                 `json:"user_id"`
	Title        pgtype.Text           `json:"title"`
	DidToday     pgtype.Text           `json:"did_today"`
	LearnedToday pgtype.Text           `json:"learned_today"`
	Category     NullJournalCategory   `json:"category"`
	Blockers     pgtype.Text           `json:"blockers"`
	NextPlan     pgtype.Text           `json:"next_plan"`
	Visibility   NullJournalVisibility `json:"visibility"`
	KpiPeriodID  pgtype.Int4           `json:"kpi_period_id"`
}

func (q *Queries) UpdateJournal(ctx context.Context, arg UpdateJournalParams) (Journal, error) {
	row := q.db.QueryRow(ctx, updateJournal,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.DidToday,
		arg.LearnedToday,
		arg.Category,
		arg.Blockers,
		arg.NextPlan,
		arg.Visibility,
		arg.KpiPeriodID,
	)
	var i Journal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EntryDate,
		&i.Title,
		&i.DidToday,
		&i.LearnedToday,
		&i.Category,
		&i.Blockers,
		&i.NextPlan,
		&i.Visibility,
		&i.KpiPeriodID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
