/**
 * calibrationExportUtils.js
 * Generates a Markdown calibration summary document for team calibration meetings.
 */

/**
 * Generates a Markdown document summarizing team calibration data.
 * 
 * @param {Object} params
 * @param {string} params.periodLabel - Display label for the review period
 * @param {string} params.managerName - Name of the reviewing manager
 * @param {string} params.teamName - Name of the team
 * @param {Object} params.summary - Team summary metrics
 * @param {Array} params.members - Team member overview objects
 * @param {Array} params.quietHeroes - Members flagged as quiet heroes
 * @param {Object} params.notesMap - Map of targetUserId → note text
 * @param {Array} params.recentAchievements - Recent team achievements
 * @returns {string} Formatted Markdown string
 */
export function generateCalibrationMarkdown({
  periodLabel,
  managerName,
  teamName,
  summary,
  members,
  quietHeroes = [],
  notesMap = {},
  recentAchievements = [],
}) {
  const lines = [];
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  });

  lines.push(`# Team Calibration Summary`);
  lines.push(``);
  lines.push(`**Period:** ${periodLabel}`);
  lines.push(`**Manager:** ${managerName}`);
  lines.push(`**Team:** ${teamName} (${summary?.total_members || members.length} members)`);
  lines.push(`**Generated:** ${date}`);
  lines.push(``);
  lines.push(`---`);
  lines.push(``);

  // Team Metrics
  lines.push(`## Team Metrics`);
  lines.push(``);
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Total Entries | ${summary?.total_journals || 0} |`);
  lines.push(`| Total Achievements | ${summary?.total_achievements || 0} |`);
  lines.push(`| Team IWQ | ${summary?.team_iwq_percentage || 0}% |`);
  lines.push(`| Foundation Entries | ${summary?.foundation_journals || 0} |`);
  lines.push(``);

  // Quiet Heroes
  if (quietHeroes.length > 0) {
    lines.push(`## Foundation Contributors`);
    lines.push(``);
    lines.push(`> The following team members contributed significantly above the team average in foundation work during this period.`);
    lines.push(``);
    for (const hero of quietHeroes) {
      lines.push(`- **${hero.name}** — ${hero.iwq_percentage}% Foundation Work (team avg: ${summary?.team_iwq_percentage || 0}%)`);
    }
    lines.push(``);
  }

  // Member Profiles
  lines.push(`## Member Profiles`);
  lines.push(``);

  for (const member of members) {
    lines.push(`### ${member.name} (${member.role})`);
    lines.push(``);
    lines.push(`- **Entries:** ${member.total_journals} | **Active Days:** ${member.active_days} | **Achievements:** ${member.total_achievements}`);
    lines.push(`- **IWQ:** ${member.iwq_percentage}% (${member.foundation_journals} foundation entries)`);

    if (member.critical_achievements > 0 || member.high_achievements > 0) {
      const parts = [];
      if (member.critical_achievements > 0) parts.push(`${member.critical_achievements} Critical`);
      if (member.high_achievements > 0) parts.push(`${member.high_achievements} High-Impact`);
      lines.push(`- **Achievement Breakdown:** ${parts.join(', ')}`);
    }

    if (member.last_entry_date) {
      const lastDate = new Date(member.last_entry_date).toLocaleDateString('en-US', {
        year: 'numeric', month: 'short', day: 'numeric',
      });
      lines.push(`- **Last Documented:** ${lastDate}`);
    }

    // Manager note for this member
    const note = notesMap[member.id];
    if (note && note.trim()) {
      lines.push(``);
      lines.push(`> **Manager Note:** ${note.trim()}`);
    }

    lines.push(``);
  }

  // Recent Achievements
  if (recentAchievements.length > 0) {
    lines.push(`## Recent Achievements`);
    lines.push(``);
    lines.push(`| Member | Achievement | Importance | Date |`);
    lines.push(`|--------|-------------|------------|------|`);
    for (const ach of recentAchievements.slice(0, 10)) {
      const achDate = ach.achieved_date
        ? new Date(ach.achieved_date).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })
        : '—';
      lines.push(`| ${ach.user_name} | ${ach.title} | ${ach.importance || 'medium'} | ${achDate} |`);
    }
    lines.push(``);
  }

  lines.push(`---`);
  lines.push(`*Generated by TRACE — Every contribution, traced.*`);

  return lines.join('\n');
}

/**
 * Copies text to the clipboard.
 * @param {string} text
 * @returns {Promise<boolean>}
 */
export async function copyToClipboard(text) {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    // Fallback for older browsers
    const textarea = document.createElement('textarea');
    textarea.value = text;
    textarea.style.position = 'fixed';
    textarea.style.opacity = '0';
    document.body.appendChild(textarea);
    textarea.select();
    document.execCommand('copy');
    document.body.removeChild(textarea);
    return true;
  }
}

/**
 * Downloads text as a file.
 * @param {string} content
 * @param {string} filename
 */
export function downloadAsFile(content, filename) {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
